default_state = "PowerOn"

[[states]]
name = "PowerOn"

[[states]]
name = "Manual"

[[states]]
name = "Safe"

[[states]]
name = "Armed"

[[states.checks]]
name = "Altitude"
check = "altitude"
condition = "greater_than"
value = 200.0
transition = "Flight"

[[states.checks]]
name = "Pyro1"
check = "pyro1_continuity"
action = "flag_set"
abort = "Safe"

[[states.checks]]
name = "Pyro2"
check = "pyro2_continuity"
action = "flag_set"
abort = "Safe"

[[states.commands]]
object = "dataRate"
value = 1000
time = 0.0

[[states]]
name = "Flight"

[[states.checks]]
name = "Apogee"
check = "apogee_flag"
action = "flag_set"
transition = "Apogee"

[[states]]
name = "Apogee"
timeout = { time = 0.0, transition = "Decent" }

[[states]]
name = "Descent"
delay = 4.0
timeout = { time = 15.0, transition = "End" }

[[states.commands]]
object = "dataRate"
value = 500
time = 0.0

[[states]]
name = "Parachute"

[[states.commands]]
object = "pyro1"
value = 1.0

[[states.commands]]
object = "pyro2"
value = 1.0
delay = 10.0

[[states]]
name = "Recovery"

[[states.commands]]
object = "beacon"
value = 1.0
time = 0.0
