[package]
name = "blursed-serde"
version = "0.1.0"
edition = "2018"

[lib]
name = "blursed_serde"

crate-type = ["cdylib", "rlib"]

[dependencies]
serde = "1.0.130"
postcard = "0.7.2"
heapless = "0.7.5"
serde_json = "1.0"

[dependencies.pyo3]
version = "0.14.5"
features = ["extension-module"]
